export const UPDATE_PACKAGE_LIST = 'UPDATE_PACKAGE_LIST';
export const UPDATE_TOTAL_COUNT = 'UPDATE_TOTAL_COUNT';
export const UPDATE_IS_POPUP = 'UPDATE_IS_POPUP';
export const UPDATE_PACKAGE_NAME = 'UPDATE_PACKAGE_NAME';
export const UPDATE_SEARCH_TEXT = 'UPDATE_SEARCH_TEXT';
export const UPDATE_PAGINATION_DATA = 'UPDATE_PAGINATION_DATA';

export default {
    UPDATE_PACKAGE_LIST,
    UPDATE_TOTAL_COUNT,
    UPDATE_IS_POPUP,
    UPDATE_PACKAGE_NAME,
    UPDATE_SEARCH_TEXT,
    UPDATE_PAGINATION_DATA,
}

